<?php

declare(strict_types=1);

/*
 * This file is part of the UhifadhiLabs Patrol Module.
 *
 * (c) Ezekiel Mjema <https://github.com/eemjema>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Uhifadhi\Patrol\Tests\Unit;

use Uhifadhi\Bundle\AreaBundle\AreaBundle;
use Uhifadhi\Bundle\AtlasBundle\AtlasBundle;
use Uhifadhi\Bundle\ShellBundle\ShellBundle;
use Uhifadhi\Bundle\ShellBundle\Test\VocabularyConformanceTestCase;
use Uhifadhi\Storage\UhifadhiStorageBundle;

/**
 * THE PATROL SCREENS SPEND NO CLASS, TOKEN OR GLYPH NOBODY SHIPS.
 *
 * THE CHAIN IS THE SHEETS A PAGE ACTUALLY LINKS, in the order
 * templates/base.html.twig links them: the atlas's map chrome, the shell's
 * widget library sheet — the dashboard IS a widget surface, so every page links
 * that one — the file-preview overlay's, the area's, whose overview page renders
 * this module's six contributions, and then this module's own two, last because
 * they are the ones allowed to decorate. Leaflet's own sheet is left
 * out: it is a vendored library rather than a vocabulary, and its selectors are
 * generated by the script that builds the map.
 *
 * @see VocabularyConformanceTestCase
 */
final class VocabularyConformanceTest extends VocabularyConformanceTestCase
{
    protected static function bundlePath(): string
    {
        return \dirname(__DIR__, 2);
    }

    protected static function alias(): string
    {
        return 'patrol';
    }

    /**
     * Two: the module's own vocabulary, and the observation-taxonomy admin's,
     * which is the one screen that links a second sheet of its own.
     *
     * @return list<string>
     */
    protected static function ownStylesheets(): array
    {
        return ['patrol.css', 'taxonomy.css'];
    }

    /** @return list<string> */
    protected static function linkedStylesheets(): array
    {
        return [
            ...parent::linkedStylesheets(),
            self::publicDirOf(ShellBundle::class).'/widget.css',
            self::publicDirOf(AtlasBundle::class).'/map.css',
            // The six overview partials are rendered by AreaBundle's own
            // overview page, which links that bundle's sheet beside this one.
            self::publicDirOf(AreaBundle::class).'/area.css',
            // The storage bundle's class sits under src/, so its public/ is one
            // level further up than a core bundle's.
            self::publicDirOf(UhifadhiStorageBundle::class, 2).'/preview.css',
        ];
    }

    /**
     * THE MODULE DRAWS NO MAP OF ITS OWN.
     *
     * Every map on the platform is the atlas's plate: a module states what is on
     * it in PHP and calls render_map(), which mounts one controller and links one
     * Leaflet. A module template that names a map controller of its own, or
     * reaches for Leaflet directly, has started a second answer to a settled
     * question — a map that looks and behaves unlike every other map in the
     * product, and, with Leaflet, a second module namespace whose layers the
     * real map refuses.
     */
    public function testNoTemplateDrawsAMapOfItsOwn(): void
    {
        $offenders = [];
        foreach (self::templateFiles() as $file) {
            // What a template EMITS, so a comment explaining where the map comes
            // from is not read as a map.
            $markup = (string) preg_replace('/\{#.*?#\}/s', '', (string) file_get_contents($file));
            $name = basename($file);

            if (preg_match('/data-controller="[^"]*(map|plate)[^"]*"/i', $markup, $matches)
                && !str_contains($matches[0], 'atlas-bundle--map-plate')) {
                $offenders[] = $name.': '.$matches[0];
            }

            // The atlas's own stylesheet constant names the sheet, not the
            // library; anything else spelling "leaflet" is reaching past the
            // plate for the map itself.
            if (preg_match('/leaflet/i', $markup)) {
                $offenders[] = $name.': leaflet';
            }
        }

        self::assertSame([], $offenders, 'a module draws no map of its own: state it in PHP and call render_map()');
    }

    /**
     * AND SHIPS NO MAP CONTROLLER EITHER.
     *
     * The template check above catches a map controller a template MOUNTS. This
     * catches one the package merely ships — a file in assets/, or an entry in
     * the package's own controllers block, that reaches for Leaflet or builds a
     * map. Flex maintains that block in the host's controllers.json, so a
     * controller declared here is a controller loaded on every page whether a
     * template names it or not.
     */
    public function testTheModuleShipsNoMapControllerAtAll(): void
    {
        $offenders = [];
        foreach (glob(self::bundlePath().'/assets/controllers/*.js') ?: [] as $file) {
            $source = (string) file_get_contents($file);
            $name = basename($file);

            if (preg_match('/\bleaflet\b|window\.L\b|uhifadhi\/(basemaps|boundary|map-chrome)/i', $source, $matches)) {
                $offenders[] = $name.': '.$matches[0];
            }
        }

        $manifest = (string) file_get_contents(self::bundlePath().'/assets/package.json');
        /** @var array{symfony?: array{controllers?: array<string, mixed>}} $declared */
        $declared = json_decode($manifest, true, 512, \JSON_THROW_ON_ERROR);
        foreach (array_keys($declared['symfony']['controllers'] ?? []) as $controller) {
            if (preg_match('/map|plate/i', (string) $controller)) {
                $offenders[] = 'package.json: '.$controller;
            }
        }

        self::assertSame([], $offenders, 'every map on the platform is the atlas\'s plate; a module ships no map controller');
    }

    /**
     * AND DRAWS NO CHART, NO MONTH AND NO MARK OF ITS OWN EITHER.
     *
     * THE ATLAS IS THE COMPONENT LIBRARY FOR EVERY MODULE VISUAL — charts,
     * calendars, map plates and their legends. A module states what is on one
     * in PHP and calls `atlas_chart()`, `atlas_calendar()` or `render_map()`;
     * what a bar chart, a month or a line looks like is decided once, where it
     * is drawn, for the whole product.
     *
     * THIS IS THE RULE THAT KEEPS IT THAT WAY, and it is a template rule
     * because that is where the drift starts. Three widgets here carried a
     * hand-built `<svg>` apiece — their own axis maths, their own gridlines,
     * their own bar geometry and three label styles this sheet had to ship to
     * dress them. Each was a private answer to a settled question, and none of
     * them turned over with the palette the way the atlas's do.
     *
     * THREE THINGS ARE REFUSED, each the start of a second answer:
     *
     *  - `<svg>` typed into a template. A mark comes from lucide through
     *    `ux_icon()`, which renders one from a file rather than from markup in
     *    the page; a chart comes from `atlas_chart()`. Neither leaves an
     *    `<svg>` in a template's source, so the rule is exact.
     *  - a Leaflet init. Every map is the atlas's plate (see the two tests
     *    above); this catches the library being reached for by name.
     *  - a month grid built by hand. `atlas_calendar()` ships the grid, the
     *    day head, the fixed cell, the count and the "+N more"; a module that
     *    loops 42 cells of its own is a calendar that grows with a busy week.
     *
     * Comments are stripped first, so a note explaining where the chart comes
     * from is not read as a chart.
     */
    public function testNoTemplateDrawsAVisualOfItsOwn(): void
    {
        $offenders = [];
        foreach (self::templateFiles() as $file) {
            $markup = (string) preg_replace('/\{#.*?#\}/s', '', (string) file_get_contents($file));
            $name = basename($file);

            if (str_contains($markup, '<svg')) {
                $offenders[] = $name.': <svg — a mark is ux_icon(), a chart is atlas_chart()';
            }

            // Leaflet by name: `L.map(`, `new L.…`, or the bridge's own import.
            if (preg_match('/\bL\.map\s*\(|\bnew\s+L\.|leaflet/i', $markup, $matches)) {
                $offenders[] = $name.': '.$matches[0];
            }

            // A MONTH BUILT BY HAND. The atlas's grid is reached by calling
            // atlas_calendar(); a template that loops days or weeks into cells
            // of its own is building a second one.
            if (preg_match('/\{%\s*for\s+\w*(day|week|cell)\w*\s+in\b/i', $markup, $matches)
                && !str_contains($markup, 'atlas_calendar(')) {
                $offenders[] = $name.': '.trim($matches[0]).' — the month grid is atlas_calendar()';
            }
        }

        self::assertSame([], $offenders, 'every chart, month and mark in the product is the atlas\'s or ux-icons\'; a module states one and never draws it');
    }

    /**
     * @return list<string>
     */
    private static function templateFiles(): array
    {
        $files = [];
        $directory = new \RecursiveDirectoryIterator(self::bundlePath().'/templates', \FilesystemIterator::SKIP_DOTS);
        /** @var \SplFileInfo $file */
        foreach (new \RecursiveIteratorIterator($directory) as $file) {
            if ($file->isFile() && str_ends_with($file->getFilename(), '.html.twig')) {
                $files[] = $file->getPathname();
            }
        }

        sort($files);

        return $files;
    }

    /**
     * @param class-string $bundle
     * @param int<1, max>  $levels
     */
    private static function publicDirOf(string $bundle, int $levels = 1): string
    {
        return \dirname(new \ReflectionClass($bundle)->getFileName() ?: '', $levels).'/public';
    }
}
